### ISSUE TITLE
Is it possible to implement something like regex search using keyvi

### ISSUE THREAD

**Issue by amirouche** [cliqz-oss/keyvi#124]
Is it possible to implement something like regex search using keyvi?

Thanks!

**Comment by hendrik-cliqz** [comment]
Short answer: yes

More elaborated: It is straight forward to build extractors that match a certain pattern today, e.g. a date extractor that matches all dates in the format: YYYY-MM-DD by simply creating all permutations and feeding that into a keyvi compiler. As minimization kicks in, the result FSA will just be a few kilo bytes.

It is certainly possible to build more complex regexes, e.g. containing epsilon transitions with a bit of implementation work. Supporting the full regex syntax e.g. capturing probably needs a lot of implementation work.

I suggest to take a look at Russ Cox posts about RE2 which is a regex engine based on finite state (like keyvi), e.g.

https://swtch.com/~rsc/regexp/regexp1.html
https://swtch.com/~rsc/regexp/regexp3.html

This is a very interesting read and I think most of it applies for keyvi.

**Comment by hendrik-cliqz** [comment]
@amirouche Does that answer your question?

Or do you mean search with a "regex query language" in a kv-index as opposed to using keyvi as a regular expression engine as described above?

Using regex for lookup would also be possible. There is fuzzy matching implemented in Completions (Levenshtein based) as well as GetNear(some sort of hamming distance). As you are free to implement any kind of graph traversal, it is doable but not for free. Things like suffix matching would require a special index.
