### ISSUE TITLE
Package referenced dynamic libraries into OS X wheels instead of static linkage

### ISSUE THREAD

**Issue by narekgharibyan** [cliqz-oss/keyvi#186]
- to get this done use https://pypi.python.org/pypi/delocate/

**Comment by hendrikmuhs** [comment]
Just curious: are there any technical benefits? faster loading? performance?

**Comment by narekgharibyan** [comment]
Nope, actually the only benefit is elimination of this "workaround" https://github.com/cliqz-oss/keyvi/blob/master/pykeyvi/setup.py#L139 

There is no `-static` flag for `clang` and it always prefers dynamic linkage over static one. So in order to create self contained package this kind of workarounds needs to be done, or using something like `delocate`.

BTW, `auditwheel` does exactly the same for `manylinux` packages.

**Comment by hendrikmuhs** [comment]
ok, sounds good.

**Comment by narekgharibyan** [comment]
Tested with `delocate 0.6.4` and it does not patch the wheel properly. 
So, closing this for now ...
