### ISSUE TITLE
Sigsev when trying to merge .kv file with no data

### ISSUE THREAD

**Issue by goran-cliqz** [cliqz-oss/keyvi#211]
If you add a .kv file with no entries in it and try to merge it, keyvi will fail with sigsev. Reproduce with the attached script.
[mergeSigsegv.txt](https://github.com/cliqz-oss/keyvi/files/773730/mergeSigsegv.txt)

**Comment by hendrikmuhs** [comment]
Good catch!

Somehow we always miss this case, e.g. there should be unit test for this.
