### ISSUE TITLE
Reusable buffers for compression in compiler

### ISSUE THREAD

**Issue by DavidNemeskey** [cliqz-oss/keyvi#44]
The new compressions classes should have versions of the methods that read from / write to streams.

**Comment by hendrik-cliqz** [comment]
Changing title to cover the remaining work as streams are available but not used.

By using the streams and some object pooling we should be able to improve the compiler (speed)

**Comment by hendrik-cliqz** [comment]
I realized, that "stream-support" was not what I wanted. The sstream classes are not easily reusable. @DavidNemeskey: Sorry, my bad.

I am now trying to change it, so that I pass a buffer object into the compression method.

**Comment by hendrik-cliqz** [comment]
implemented in https://github.com/cliqz-oss/keyvi/pull/49
