### ISSUE TITLE
Keyvi compilation loses some records

### ISSUE THREAD

**Issue by DavidNemeskey** [cliqz-oss/keyvi#47]
@hendrik-cliqz I have uploaded the file to s3.

**Comment by hendrik-cliqz** [comment]
I checked the file, the problem are duplicated keys. sort|uniq does not work as values are different. But if I only take the keys ans uniq them, I get exactly the count that keyviinspector has.

**Comment by hendrik-cliqz** [comment]
closing as by design. I will follow up to find out the origin of this data, it should not have these duplicates in the first place.
